// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzaria.Data.Models;

namespace Pizzaria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180712024055_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pizzaria.Data.Models.PizzaModels.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("PizzaId");

                    b.HasKey("IngredientId");

                    b.HasIndex("PizzaId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Pizzaria.Data.Models.PizzaModels.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Vegetarian");

                    b.HasKey("PizzaId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("Pizzaria.Data.Models.UserModels.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Neighborhood");

                    b.Property<int>("Number");

                    b.Property<string>("Street");

                    b.Property<int?>("UserId");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Pizzaria.Data.Models.UserModels.ConversationData", b =>
                {
                    b.Property<int>("ConversationDataId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ConversationDataId");

                    b.ToTable("ConversationDatas");
                });

            modelBuilder.Entity("Pizzaria.Data.Models.UserModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConversationDataId");

                    b.HasKey("UserId");

                    b.HasIndex("ConversationDataId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pizzaria.Data.Models.PizzaModels.Ingredient", b =>
                {
                    b.HasOne("Pizzaria.Data.Models.PizzaModels.Pizza")
                        .WithMany("Ingredients")
                        .HasForeignKey("PizzaId");
                });

            modelBuilder.Entity("Pizzaria.Data.Models.UserModels.Address", b =>
                {
                    b.HasOne("Pizzaria.Data.Models.UserModels.User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Pizzaria.Data.Models.UserModels.User", b =>
                {
                    b.HasOne("Pizzaria.Data.Models.UserModels.ConversationData", "ConversationData")
                        .WithMany()
                        .HasForeignKey("ConversationDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
